spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://39.96.18.72:3306/community?useSSL=false&serverTimezone=GMT%2B8
    driver-class-name: com.mysql.cj.jdbc.Driver
    #    不配，默认使用tomcat的数据源
    type: com.alibaba.druid.pool.DruidDataSource

  jpa:
    hibernate:
      ddl-auto: update
  thymeleaf:
    prefix: classpath:/templates/
    check-template-location: true
    suffix: .html
    encoding: UTF-8
    cache: false
    mode: LEGACYHTML5
  redis:
    database: 2
    host: 39.96.18.72
    port: 6379
    password: lxs

server:
  port: 80
#  servlet:
#    context-path: /lxs

github:
  client:
    id: 67e02325958dedeaf220
    secret: 6cd575b362cc40f51ffa5c94db443d6dcb6772d2
    uri: http://xuesenli.top:80/callback

# 驼峰标识
mybatis:
  configuration:
    map-underscore-to-camel-case: true
    #mybatis配置
  type-aliases-package: com.lxs.community.model
  mapper-locations: classpath:mapper/*.xml

##  项目日志打印
logging:
  file:
    max-size: 100MB
    max-history: 2
