spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://127.0.0.1:3306/community?useSSL=false&serverTimezone=GMT%2B8
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
  jpa:
    hibernate:
      ddl-auto: update
  #thymeleaf模板引擎
  thymeleaf:
    prefix: classpath:/templates/
    check-template-location: true
    suffix: .html
    encoding: UTF-8
    cache: false
    mode: LEGACYHTML5
  redis:
    database: 2
    host: 127.0.0.1
    port: 6379
    password: 123456

#配置静态资源
#  mvc:
#    static-path-pattern: /static/**

server:
  port: 8887

github:
  client:
    id: 67e02325958dedeaf220
    secret: 32f3cc304d49f01dcc8db405b6164ea6630a5b5d
    uri: http://localhost:8887/callback

# 驼峰标识
mybatis:
  configuration:
    map-underscore-to-camel-case: true
    #mybatis配置
  type-aliases-package: com.lxs.community.model
  mapper-locations: classpath:mapper/*.xml

##  项目日志打印
logging:
  file:
    max-size: 100MB
    max-history: 2
